spring:
  cassandra:
    contact-points:
      - cass1:9042
      - cass2:9042
      - cass3:9042
    local-datacenter: datacenter1
    keyspace-name: demo_keyspace
    schema-action: create_if_not_exists
    request:
      timeout: 10s
      consistency: one

server:
  port: 9080
